import Head from "next/head";
import Image from "next/image";
import computer from "../public/images/computer.png";
import huojian from "../public/images/huojian.png";
import bin from "../public/images/bin.jpg";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" w-[58rem] m-auto border-l-2 border-r-2">
        <div>
          <nav className=" flex flex-row  justify-between">
            <img src="https://uploads-ssl.webflow.com/61ba26b76e77f36c0ba7d282/630a6f96aba04eaff0abcaff_animedollarmascot.webp"></img>
            <div className=" inline-flex items-center justify-around w-28 text-white font-mono font-bold mr-2">
              <a>登录</a>
              <a>账号</a>
              <a>股份</a>
            </div>
          </nav>
        </div>
        <div className=" flex flex-col  w-[54rem] m-auto">
          <div
            style={{ "background-color": "rgba(254,226,226,0.3)" }}
            className=" flex flex-row justify-between items-center mt-10 shadow-2xl  rounded-md"
          >
            <div className=" ml-6 w-96  rounded-md text-center  font-bold text-white font-mono text-xl">
              <p>这是一场真实的社会实验</p>
              <p>
                <span className=" text-red-500">中国</span>
                将出现一个全新的电子商务平台
              </p>
            </div>
            <Image className=" w-96 mr-6 " src={computer} alt="fdsafsd"></Image>
          </div>
          <div
            style={{ "background-color": "rgba(254,226,226,0.3)" }}
            className=" rounded-md flex flex-row justify-between  shadow-2xl items-center  mt-10"
          >
            <Image className=" w-96 ml-6" src={computer} alt="fdsafsd"></Image>
            <div className=" mr-6 w-96 text-center  rounded-md text-white font-bold text-xl">
              <p>这个平台的名字叫“咕咚” </p>
              <p>主营年轻人的消费品</p>
              <p> 但有一点不一样</p>
              <p>咕咚平台会记录每一位用户</p>
              <p>在咕咚所做的贡献</p>
              <p>例如，您为咕咚邀请来好友</p>
              <p>或者，您在咕咚平台买卖商品</p>
              <p>皆是为咕咚做出了贡献</p>
              <p>咕咚将把这些贡献</p>
              <p>直接转化成咕咚的股份(未来的股票) </p>
              <p>免费赠送于您</p>
            </div>
          </div>
          <div
            style={{ "background-color": "rgba(254,226,226,0.3)" }}
            className=" rounded-md flex flex-row justify-between items-center shadow-2xl  mt-10"
          >
            <div className=" mr-6 w-96 text-center rounded-md text-white font-bold text-xl">
              <p>咕咚平台有可能</p>
              <p>在未来5年内</p>
              <p>超越阿里巴巴</p>
              <p>甚至超越亚马逊</p>
              <p>也就是，市值将达万亿以上</p>
              <p>（咕咚的股份总量1亿股）</p>
              <p>也就是，未来每股的价值</p>
              <p>将达万元以上</p>
              <p>也许您会觉得不可能</p>
              <p>但万一呢？</p>
            </div>
            <Image className=" w-96 mr-6" src={huojian} alt="fdsafsd"></Image>
          </div>
          <div
            style={{ "background-color": "rgba(254,226,226,0.3)" }}
            className=" rounded-md flex flex-row justify-between items-center shadow-2xl  mt-10"
          >
            <Image className=" w-96 ml-6" src={bin} alt="fdsafsd"></Image>
            <div className=" mr-6 w-96 rounded-md text-white font-bold text-xl">
              咕咚小程序/APP产品正在同步开发中，待产品上线后，咕咚的股份将以“积分”的形式显示在咕咚小程序及APP产品上，本“积分”发行总量为1亿份（永无增发），其中咕咚创始团队仅持有10%，28%预留给投资机构及团队后续扩员，2%免费空投给最早来到这里的1万名种子用户，剩余60%将分阶段、分批次免费赠予全生态用户！早来者会获得多一些，晚来者会获得少一些。
            </div>
          </div>
          <div
            style={{ "background-color": "rgba(254,226,226,0.3)" }}
            className=" rounded-md flex flex-row justify-between items-center  shadow-2xl mt-10"
          >
            <div className=" mr-6 w-96 rounded-md text-white font-bold text-xl">
              在此阶段，咕咚将2%的原始股份（200万股）免费空投给最早来到这里的1万名参与者（每人最多200股），申请方式如下：
            </div>
          </div>
        </div>
        <div className=" mb-40"></div>
      </div>
    </div>
  );
}
